# Modules
":floppy_disk: peering":
- changed-files:
  - any-glob-to-any-file:
    - modules/peering/**/*

":floppy_disk: accepter":
- changed-files:
  - any-glob-to-any-file:
    - modules/accepter/**/*

":floppy_disk: requester":
- changed-files:
  - any-glob-to-any-file:
    - modules/requester/**/*
